### ISSUE TITLE
更新大佬，请问怎样才能把顶栏颜色修改成白色呢?

### ISSUE THREAD

**Issue by muabl** [owen0o0/WebStack#1]
顶栏的导航页以及导航栏，像[狼牌导航](https://www.volf.club/) 这样，不要黑灰色。
这样可能看起来更加简洁

**Comment by muabl** [comment]
还有把logo也去掉- ̗̀(๑ᵔ⌔ᵔ๑)

**Comment by owen0o0** [comment]
这个F12找到对应的css样式改了颜色就可以了，

logo一样的找到对应的div删了
