### ISSUE TITLE
Xss vulnerability

### ISSUE THREAD

**Issue by deenrookie** [owen0o0/WebStack#14]
Our code safe check tool **Xcheck** has found two xss vulnerabilities in this project. Here are the details:

1. go.php 
`<meta http-equiv="refresh" content="0.1;url=<?php echo $b; ?>">` $b from the $_GET['url']. 
You can visit this url `https://nav.iowen.cn/go/?url=Ij48c2NyaXB0PmFsZXJ0KGB4c3NgKTwvc2NyaXB0Pg==` to verify.

2. ajax.php
line: 48 `echo '{"status":4,"msg":"图片 '.$attach_id.' 删除失败！"}';` $attach_id from the $_POST

**Comment by owen0o0** [comment]
Thanks for your feedback.
