### ISSUE TITLE
去除编辑栏

### ISSUE THREAD

**Issue by xdaoxyz** [owen0o0/WebStack#15]
hello，
请问在后台添加链接时如何去除文章编辑栏？如附件
[谢谢
https://github.com/xdaoxyz/Infrastructure/blob/master/200619084705.png

**Comment by xdaoxyz** [comment]
https://github.com/xdaoxyz/Infrastructure/blob/master/200619084705.png

**Comment by owen0o0** [comment]
inc\post-type.php 类型注册的“editor”删掉
