### ISSUE TITLE
給开发者的留言

### ISSUE THREAD

**Issue by vdnnc** [owen0o0/WebStack#18]
偶然在网站看到你的作品，导航站很美，可是不习惯用wordpress，
所以想把你这模板UI移植到我喜欢的CMS上，
我用MacCmsV10，做导航，视频，文章，小说，美图，等，，，你的这个前端太适合了！
希望这样不会对你的作品造成麻烦。。
等完成移植后，希望和贵官方站做个友情链接，备注这模板的灵感来源于你的。

**Comment by owen0o0** [comment]
嗯嗯 可以的
