### ISSUE TITLE
太黑, 年前还 99 的 wordpress 导航主题,现在要 218.

### ISSUE THREAD

**Issue by 2Githuber** [owen0o0/WebStack#20]
不仅黑, 还剽窃 webstack 原本的版面设计, 原来还剽窃名称, 叫 webstack pro. 本来打算买两个的, 结果发现一维导航 wordpress 主题不仅涨价了, 才几个月, 注册了个人独资企业, 就涨价一倍多? 还好免费的不止一个. 也只能叫一维. 有为的为, 还是别用了.

webstack官方原版设计:
https://github.com/WebStackPage/WebStackPage.github.io

**Comment by owen0o0** [comment]
就服你，开源版我明确指明了基于webstack 原本做的wordpress后台，也链接了原仓库，至于收费版，你看哪剽窃了，就结构想？这样结构的网站多的是。我卖这么久了第一次见你这号人，就因为账个价你消费不起就到处喷？

**Comment by owen0o0** [comment]
消失了...
