### ISSUE TITLE
我感觉做成插件会不会更好

### ISSUE THREAD

**Issue by musaart** [owen0o0/WebStack#21]
做成插件，单独开个导航页面会不会更好些。整个站点做成导航，还是有些奢侈啊

**Comment by 2Githuber** [comment]
不可能啊, 人家要挣钱的. 这里不过是引流罢了.

Q: Do it as a plug-in, a separate navigation page will not be better. It is still a bit extravagant to make the whole site into a navigation.

A: Impossible, they have to earn money. Here is just to attract traffic.

**Comment by owen0o0** [comment]
水煮鱼有开发，可以去试试
