### ISSUE TITLE
网页图标自动获取

### ISSUE THREAD

**Issue by bravebob** [owen0o0/WebStack#23]
您好，每个网站前的图标可以指定为本地图片吗？我的主题使用了之后，网站前的图片并没有自动更新。
![image](https://user-images.githubusercontent.com/43507667/122764499-1dcef680-d2d2-11eb-99df-f5547ecd8880.png)

**Comment by owen0o0** [comment]
可能这个api挂了，你可以找个图标api替换设置里的选项，或者手动上传图标

**Comment by owen0o0** [comment]
给你找了一个https://ico.mikelin.cn/

api地址填    https://ico.mikelin.cn/
http     关
后缀   留空

**Comment by bravebob** [comment]
多谢！

**Comment by owen0o0** [comment]
![iowen_2019-08-27_01-05-39](https://user-images.githubusercontent.com/32561126/130360710-f6d7857e-24f3-4bc9-a9b1-1901cf67fed4.png)
![Uploading iowen_2019-08-27_01-22-37.png…]()
