### ISSUE TITLE
保存网址之后再次编辑网址，网址链接属性的设置内容丢失了

### ISSUE THREAD

**Issue by 794051908** [owen0o0/WebStack#25]
![image](https://user-images.githubusercontent.com/56404668/139052059-c9c157c4-6095-41cd-b8eb-c5df72fb73ff.png)
这里面填写有内容更新网址之后，前端也显示正常。再进来编辑的时候，这儿位置是空的。

**Comment by owen0o0** [comment]
不存在此问题，请自查一下

**Comment by HultimateH** [comment]
我在使用中也遇到了这个问题， 只要点更新，链接，序号等参数就没了，需要重新填写

![2](https://user-images.githubusercontent.com/18096197/141890965-48f2cd00-8b96-4f3b-a41f-aab4ee691009.gif)

**Comment by live-4k** [comment]
反馈一下，也遇此问题。1522 1597新手使用有此问题，旧版则无。环境php 7.2 wp5.7 bt

**Comment by Anrufen** [comment]
我是点发布之后当前页面就没有这些信息了 - - php7.2，wp5.8

**Comment by liu1013269528** [comment]
确实有这个问题，作者可以修复一下

**Comment by owen0o0** [comment]
已经修复，不知道什么原因造成了和我演示站不一样的一句代码，今天对比了一下才发现，不好意思各位😥
