### ISSUE TITLE
恳请适配iPad布局

### ISSUE THREAD

**Issue by FanyangMengDev** [owen0o0/WebStack#3]
一为大佬您好，我在您博客留了言，并且已经将我的iPad截图发给了您。
目前的这个主题在iPad上面完全是错乱的，恳请适配。适配之后我愿意资助一波。

**Comment by owen0o0** [comment]
我下下来替换试一下，https://github.com/owen0o0/WebStack/archive/master.zip

**Comment by FanyangMengDev** [comment]
依然是我给您发的截图的样子没变

**Comment by owen0o0** [comment]
替换后在后台重新设置一下“网址列数”，然后保存设置，一个可以了，你可以访问我的导航站试试

**Comment by FanyangMengDev** [comment]
哦哦！原来是还得重新选择列数，这下可以了！非常感谢大佬！真的太强了！
