### ISSUE TITLE
演示站首页滑动页面数据混乱且重复。

### ISSUE THREAD

**Issue by appstack** [owen0o0/WebStack#30]
![image](https://user-images.githubusercontent.com/58589459/170495686-6faa5671-589a-476f-93b2-95352d75b2a5.png)

**Comment by mcyydscc** [comment]
我也出现了这种情况，有什么解决办法吗

**Comment by owen0o0** [comment]
wp暂时用5.8的版本，得空我再更新

**Comment by ivkeji** [comment]
附议

**Comment by appstack** [comment]
静等作者更新程序，群主的演示站已经解决了这一问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "owen0o0/WebStack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月23日(星期四) 晚上10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [owen0o0/WebStack] 演示站首页滑动页面数据混乱且重复。 (Issue #30)





 
附议

**Comment by owen0o0** [comment]
https://github.com/owen0o0/WebStack/issues/32
