### ISSUE TITLE
提交一个bug（锚点如果文字不相连就无法跳转）

### ISSUE THREAD

**Issue by mrseawood** [owen0o0/WebStack#39]
举个例子
比如我的链接分类是

这是第一个分类
这是第二个分类
这是第三个分类
这是第四个分类 

以上四个分类如果分别点击是可以正常跳转到相应分类的

如果分类变成如下

这 是 第 一 个 分 类
这 是 第 二 个 分 类
这 是 第 三 个 分 类
这 是 第 四 个 分 类 

这个时候点击任意一个分类都无法正常跳转了

因为我用的是英文站所以分类会变成

The first  category
The second category
The third category
The fourth category

这个时候点击任意一个分类也是无法跳转的

不知道这算不算一个bug，或者只是我出现了这个问题
在这里谢谢作者提供的免费主题

**Comment by owen0o0** [comment]
确实有这问题，晚点修复

**Comment by owen0o0** [comment]
更新了，试试
