### ISSUE TITLE
无法进入详细页面

### ISSUE THREAD

**Issue by llw-code** [owen0o0/WebStack#49]
**无法进入详细页面**
详情页
显示网址详情页开启后
<img width="582" alt="屏幕截图 2023-04-16 083115" src="https://user-images.githubusercontent.com/123876746/232260006-1747ca83-59ad-40af-adaf-8e0841bc83e4.png">

点击链接，会新开一个页面地址会发生变化，但显示的内容是还是主页的内容
<img width="716" alt="屏幕截图 2023-04-16 083704" src="https://user-images.githubusercontent.com/123876746/232260058-13307f0d-fac3-411d-b902-f436dec9c111.png">

**Comment by llw-code** [comment]
<img width="718" alt="屏幕截图 2023-04-16 083929" src="https://user-images.githubusercontent.com/123876746/232260116-ee81daec-b063-4d29-8709-fe414a0e0b87.png">
进不去这个页面

**Comment by llw-code** [comment]
<img width="835" alt="屏幕截图 2023-04-16 084622" src="https://user-images.githubusercontent.com/123876746/232260289-b4d262d2-87a6-46ea-afda-93aa92a27fc7.png">


已经解决 固定链接结构 改为文章名就行了

**Comment by owen0o0** [comment]
只要不是第一个都行
