### ISSUE TITLE
额，不建议用知心天气API

### ISSUE THREAD

**Issue by 867342200** [owen0o0/WebStack#5]
知心天气贼坑了，用着用着就用不了了，非常的坑。现在用感觉没事，过一阵子就会发现问题了。建议作者把知心天气改成 和风天气，没有使用限制。

[https://dev.heweather.com/widget/simple](url)

[https://www.520iloveyou.vip/index.php/archives/84/](url)

**Comment by owen0o0** [comment]
这感觉差不多，出问题了再换把，我弄个简单说明有需要的自己更换把

**Comment by owen0o0** [comment]
换成和风了，感觉比知心快一点点
