### ISSUE TITLE
几个功能小建议

### ISSUE THREAD

**Issue by FanyangMengDev** [owen0o0/WebStack#6]
一为大佬您好，经历了长期的使用之后我发现了几个使用上可以改进的地方，想提几个建议不知道可行性高不高：

1. 增加单独页面快速调整网站排名数字
这一点主要是因为自己的网站有很多的导航，如果某一天忽然需要加一个在中间的话，需要调整后续网站的排名数字，一个一个点进去改特别麻烦效率也非常低，我目前想的就是要是能有一个页面单独就只有网址和数字，那这样或许会编辑排名快很多。如果大佬有什么能加速这个排名调整的方法那更好。 

2. 增加站内搜索引擎
因为平常用手机比较多，电脑如果搜索导航页面的某个网站其实很快，ctrl+F直接能搜到，但是手机的话有很多不方便的地方，不好直接定位到相关位置，要是能增加一个站内搜索功能是最好的了，这样能方便快速找到需要的网站。

我目前就这两点对功能的想法，不知道可能性高不高，但是很期待一为哥能做到这两个功能，这将对导航页的设计起到非常大的帮助！

感谢！

**Comment by owen0o0** [comment]
第一个能力有限，没想到这么做，第二个已经添加了，等待下次更新吧
